version: '3'

services:
  db:
    image: postgres:alpine
    container_name: db_container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tabel
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./test_data:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    environment:
      - DBUSER=user
      - DBPASS=pass
      - DBNAME=tabel
      - DBHOST=db
      - API_GITHUB=YOURE_API
    networks:
     - my_network
    depends_on:
      - db
    volumes:
      - ./logs:/log

  url_app:
    build:
      context: .
      dockerfile: Dockerfile_help_url
    container_name: help_url
    environment:
      - DBUSER=user
      - DBPASS=pass
      - DBNAME=tabel
      - DBHOST=db
      - API_GITHUB=YOURE_API
    networks:
     - my_network
    depends_on:
      - db

networks:
  my_network:
