FROM python:slim-bookworm

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt && mkdir /log

COPY .. .

CMD ["python", "help_url_next.py"]

